//로그인 테이블
CREATE TABLE POOSILMEMBERS(
	MEBERID VARCHAR2(30) NOT NULL,
	PASSWORD VARCHAR2(100) NOT NULL,
	USERNAME VARCHAR2(100)NOT NULL,
	USERNICKNAME VARCHAR2(100) NOT NULL,
	USEREMAIL VARCHAR2(100) NOT NULL,
	USERPHONE NUMBER(30) NOT NULL,
	ADDRESS VARCHAR2(100) NOT NULL,
	AVARTAR VARCHAR2(4000),
	USERROLE VARCHAR2(10) NOT NULL,
	USERENABLED VARCHAR2(10) NOT NULL,
	CONSTRAINT POOSILMEMBERS_PK PRIMARY KEY(USERID),
	CONSTRAINT POOSILMEMBERS_UQ UNIQUE(USEREMAIL),
	CONSTRAINT POOSILMEMBERS_USERENABLED_CHK CHECK(USERENABLED IN ('Y','N'))
);



//ADMIN 회원가입
INSERT INTO POOSILMEMBERS(USERID,PASSWORD,USERNAME,
						USERNICKNAME,USEREMAIL,USERPHONE,
						ADDRESS,AVARTAR,USERROLE,USERENABLED
) VALUES('ADMIN','123123','한우빈','관리자','admin@123','123123','우리집',NULL,'ADMIN','Y');

//USER회원가입
INSERT INTO POOSILMEMBERS(USERID,PASSWORD,USERNAME,
						USERNICKNAME,USEREMAIL,USERPHONE,
						ADDRESS,AVARTAR,USERROLE,USERENABLED
						
) VALUES('qweqwe','123123','우빈','유저','USER@345','123123','우리집',NULL,'USER','Y');

SELECT USERID, PASSWORD,USERNAME,USERNICKNAME,USEREMAIL,USERPHONE,ADDRESS,AVARTAR,USERROLE,USERENABLED
FROM POOSILMEMBERS
WHERE USERID = 'ADMIN' AND PASSWORD = '123123';

//ID중복체크
SELECT USERID, PASSWORD,USERNAME,USERNICKNAME,USEREMAIL,USERPHONE,ADDRESS,AVARTAR,USERROLE,USERENABLED
FROM POOSILMEMBERS
WHERE USERID = 'USER';

//정보조회(MYPAGE)
SELECT USERID, PASSWORD,USERNAME,USERNICKNAME,USEREMAIL,USERPHONE,ADDRESS,AVARTAR,USERROLE,USERENABLED
FROM POOSILMEMBERS
WHERE USERID = 'USER';

//전체조회
SELECT * FROM POOSILMEMBERS

//회원탈퇴(정보유지)
SELECT USERID USERENABLED FROM MEMBERS
WHERE USERENABLED ='N';











// TEST
DROP TABLE PAYTESTMEMBERS
CREATE TABLE PAYTESTMEMBERS(
	MEMBER_ID VARCHAR2(30) NOT NULL,
	MEMBER_PW VARCHAR2(100) NOT NULL,
	MEMBER_AGE NUMBER NOT NULL
)
SELECT * FROM PAYTESTMEMBERS

INSERT INTO PAYTESTMEMBERS(MEMBER_ID,MEMBER_PW,MEMBER_AGE) 
VALUES('USER01','123123',29)









