CREATE SEQUENCE PAY_NO

CREATE TABLE TESTPAYTABLE(
	PAY_NO NUMBER, 
	PAY_PRICE VARCHAR2(100) NOT NULL,
	PAY_DATA VARCHAR2(3000) NOT NULL,
	PAY_DATE DATE NOT NULL,
	PAY_ID VARCHAR2(30),NOT NULL,
	CONSTRAINT TESTPAYTABLE_PK PRIMARY KEY (PAY_NO),
	CONSTRAINT TESTPAYTABLE_PAY_ID_FK FOREIGN KEY (PAY_ID) REFERENCES PAYTESTMEMBERS (MEMBER_ID)
)


SELECT * FROM TESTPAYTABLE

SELECT * FROM  ALL_COL_COMMENTS  
WHERE TABLE_NAME ='PAYTABLE'

INSERT INTO PAYTABLE
VALUES (PAY_NO.NEXTVAL,'5000','회원권',SYSDATE,'user2')

SELECT * FROM MEMBER

UPDATE MEMBER SET MEMBER_ENABLED ='Y'
WHERE MEMBER_ID = 'user'



SELECT * FROM PAYTABLE















